version: 0.2

env:
  variables:
    DEV_BRANCH: dev
    RELEASE_BRANCH: master
    REPO: ebx/ebx-jobqueue-sdk
    BASE_BUILD_EMAIL_RECIPIENT: backend-deployments-group@echobox.com
    BUILD_SCRIPTS_DIR: Infrastructure/Build-Scripts
    BUILD_DOCKER_DIR: Infrastructure/Build-Docker
    BUILD_HELM_DIR: Infrastructure/Build-Helm
    INFRASTRUCTURE_CDK_DIR: Infrastructure/Build-Infrastructure
    HELM_REPO_S3_BUCKET: echobox-helm-charts
    HELM_REPO_NAME: echobox
  parameter-store:
    BUILD_EMAIL: '/Prod/Internal/Build-Email'
    README_TOKEN: '/Prod/External/Readme.io/APIToken'
  secrets-manager:
    GITHUB_TOKEN: '/Prod/External/Github/APIToken-SupportAtEchoboxCom'

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - ## install python3 to allow build_docs.py to run
      - apt-get update
      - apt install -y python3-pip
      - pip install --upgrade pip
      - pip --version
      - apt install -y dos2unix

  pre_build:
    commands:
      - ## Confirm build versions
      - docker --version
      - java -version
      - ## BOOTSTRAP Script - must run first !!
      - chmod a+x ${BUILD_SCRIPTS_DIR}/get_latest_buildscripts.sh
      - ${BUILD_SCRIPTS_DIR}/get_latest_buildscripts.sh
 
  build:
    commands:
      - ## get the current branch based upon the pipeline settings
      - CURRENT_BRANCH=$(sh ${BUILD_SCRIPTS_DIR}/get_current_git_branch.sh)
      - # output test message
      - echo "Running pipeline for REPO - ${REPO}, BRANCH - ${CURRENT_BRANCH}"

  post_build:
    commands:
      - ## will send email if codebuild was triggered from pipeline and codebuild was successful
      - ## first create the helm report - and include that in the email
      - ${BUILD_SCRIPTS_DIR}/build_helm_package_notes.sh
      - ${BUILD_SCRIPTS_DIR}/send_email_notification.sh

cache:
  paths:
    - '/root/.m2/**/*'
